%YAML:1.0
---
model_type: PINHOLE
camera_name: camera
image_width: 640
image_height: 480
distortion_parameters:
   k1: 0.0
   k2: 0.0
   p1: 0.0
   p2: 0.0
projection_parameters:
   fx: 389.9181823730469
   fy: 389.9181823730469
   cx: 321.11053466796875
   cy: 242.36834716796875